doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: false
    mappings:
      Job:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/Job/Persistence/Mapping"
        prefix: 'App\Job\Domain\Entity'
        alias: Job
      User:
        is_bundle: false
        type: xml
        dir: "%kernel.project_dir%/src/User/Persistence/Mapping"
        prefix: 'App\User\Domain\Entity'
        alias: User